# Generated by Django 5.0.4 on 2024-04-12 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=50)),
                ('is_valid', models.BooleanField(default=False)),
                ('isSyntaxValid', models.BooleanField(default=False)),
                ('isMailServerDefined', models.BooleanField(default=False)),
                ('isKnownSpammerDomain', models.BooleanField(default=False)),
                ('isDisposableEmailAddress', models.BooleanField(default=False)),
            ],
        ),
    ]
