# Generated by Django 5.0.4 on 2024-04-12 23:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_validation_app', '0002_rename_isdisposableemailaddress_email_isdisposable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email_address',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
