# Generated by Django 5.0.4 on 2024-04-15 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_validation_app', '0003_alter_email_email_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='user',
        ),
    ]
