# Generated by Django 5.0.4 on 2024-04-12 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('is_valid', models.BooleanField(default=False)),
                ('country_name', models.CharField(max_length=30)),
                ('localityLanguage', models.CharField(max_length=3)),
                ('location', models.CharField(max_length=50)),
                ('countryFlagEmoji', models.CharField()),
            ],
        ),
    ]
