# Generated by Django 5.0.4 on 2024-04-12 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone_validation_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='localityLanguage',
            new_name='countryCode',
        ),
    ]
