# Generated by Django 5.0.4 on 2024-04-14 04:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_validation_app', '0004_alter_phone_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='phone_number',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^\\+(?:[0-9] ?){6,14}[0-9]$')]),
        ),
    ]
