# Generated by Django 5.0.4 on 2024-04-14 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_validation_app', '0005_alter_phone_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='countryFlagEmoji',
            field=models.CharField(default='🇺🇸', max_length=10),
        ),
    ]
