# Generated by Django 5.0.4 on 2024-04-18 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_validation_app', '0006_alter_phone_countryflagemoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='isKnownSpammerDomain',
            field=models.BooleanField(default=False),
        ),
    ]
