# Generated by Django 5.0.4 on 2024-04-18 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone_validation_app', '0007_phone_isknownspammerdomain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='isKnownSpammerDomain',
        ),
    ]
